### PR TITLE
Update to av11

### PR DESCRIPTION
**Pull request by alexalok**
Hi! 

Thank you for your library, I find it really useful. Since I am using Avalonia 11 I took it upon myself to try and port your library to it. I am quite new to Avalonia so there might be something left to improve. I am open for amendments.

### CODE REVIEW

**Comment by EtherGhost** [comment]
Tragic to see how project like this gets abandoned...

**Comment by pr8x** [comment]
@EtherGhost I would love to merge the PR if OP responds to my review.

**Comment by alexalok** [comment]
Hey @pr8x, is there anything I should do on my side? Thanks.

**Comment by pr8x** [comment]
@alexalok I left some comment here: https://github.com/pr8x/DesktopNotifications/pull/23#discussion_r1279370172

**Comment by EtherGhost** [comment]
> @EtherGhost I would love to merge the PR if OP responds to my review.

Ok, my bad! Sorry!

**Comment by alexalok** [comment]
@pr8x I can't see this comment for some reason. Perhaps you could re-review or post a comment separately?

**Review by pr8x — APPROVED** [review]

**Comment by pr8x** [comment]
@alexalok Seems that I did not submit the review on GitHub. Sorry for the inconvenience. It was only a NIT anyways. Approved the PR & thanks for contributing!

**Comment by pr8x** [comment]
@alexalok Now that `AvaloniaLocator` is removed I am not even sure if we need the `DesktopNotifications.Avalonia` package at all. Users can easily create the notification manager without going through the `AppBuilder`... and it would probably be better since `AppBuilder` is not async anyways. What do you think? Of course, we can keep the Example code showcasing the notification manager in an Avalonia application.

**Comment by alexalok** [comment]
@pr8x, sorry for the delayed response. I think the package could still be beneficial due to `AppBuilderExtensions.SetupDesktopNotifications` method. It can also help being more explicit in that the library supports Avalonia.

**Pull request merged**
